services:
  - type: web
    name: slack-nextjs-service
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: slack-backend-service
    plan: free
    env: node
    rootDir: api
    buildCommand: npm install && npm run build && npx prisma db push
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 14
      - key: DATABASE_URL
        fromDatabase:
          name: slack-database
          property: connectionString
    healthCheckPath: /healthz

databases:
  - name: slack-database
    databaseName: slack
