services:
  - type: web
    name: slack-nextjs-service
    env: node
    rootDir: web
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://slack-backend-service.onrender.com

  - type: web
    name: slack-backend-service
    plan: free
    env: node
    rootDir: api
    buildCommand: npm install &&  npx prisma generate && npm run build && npx prisma db push
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 14
      - key: DATABASE_URL
        fromDatabase:
          name: slack-database
          property: connectionString
      - key: FRONTEND_URL
        value: https://slack-nextjs-service.onrender.com
    healthCheckPath: /healthz

databases:
  - name: slack-database
    databaseName: slack
