databases:
  - name: slack-database
    databaseName: slack
    user: shawn
services:
  - type: web
    name: slack-backend-service
    plan: free
    env: node
    rootDir: api
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        sync: false
