databases:
  - name: slack-database
    databaseName: slack
    user: shawn
services:
  - type: web
    name: slack-backend-service
    plan: free
    env: node
    rootDir: api
    buildCommand: cd api && npm install && npm run build
    startCommand: cd api && npm run start
    healthCheckPath: /
